config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'static_pages#home'

  # get '/p',   to: 'posts#new', as: 'p'

  get 'sessions/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :posts, only: %i[new create index]
  resources :users, only: [:create, :new]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :token
  before_create :remember
  before_save { self.email = email.downcase }
  has_many :posts

  validates :username, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_secure_password

  def self.new_token
    token = SecureRandom.urlsafe_base64
    Digest::SHA1.hexdigest(token.to_s)
  end

  def change_token
    self.token = User.new_token
    update_attribute(:remember_token, token)
  end

  private

  def remember
    self.remember_token = User.new_token
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :user_logged_in, only: %i[new create]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id

    if @post.valid?
      @post.save
      flash[:success] = 'Article published successfully'
      redirect_to posts_url
    else
      flash.now[:danger] = "Title/content fields shouldn't be blank"
      render 'new'
    end
  end

  private

  def user_logged_in
    return if logged_in?

    flash[:danger] = 'You are not logged in / please login to be able to see the articles'
    redirect_to login_url
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      log_in user
      remember user
      flash[:success] = 'Welcome back you are in!'
      redirect_to root_url
    else
      flash.now[:danger] = 'Invalid Username/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = 'Logged out successfully, come back soon!'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :user_logged_out, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'You have signed up successfully!'
      log_in @user
      redirect_to root_url
    else
      flash.now[:danger] = 'There has been an error'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def user_logged_out
    return unless logged_in?

    flash[:danger] = 'You have to logout first'
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.change_token
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      log_in user if user&.authenticate(cookies[:remember_token])
    end
  end

  def sign_out
    session.delete(:user_id)
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer col-md-12">
    <small class="footer-small">
        The <a href="https://github.com/Redvanisation/members-only" target="_blank">Members Only App</a>
        coded by <a href="https://github.com/Redvanisation" target="_blank">Redvan</a> and 
        <a href= "https://github.com/MouhaDiouf" target="_blank">Mouhamadou</a>
    </small>
</footer>

app/views/layouts/_head.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Members Only", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Articles", posts_path %></li>
                <% if logged_in? %>
                    <li><%= link_to "New Article", new_post_path %></li>
                    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                <% else %>
                    <li><%= link_to "Login", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Members Only</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/head' %>
      
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1 class="margin-bottom-big">All Articles List</h1>

<%= will_paginate %>

<% @posts.each do |post| %>
<div class="article">
    <h3 class="article-title center"><%= post.title %></h3>
    <p class="article-body capital-firstl"><%= post.content %></p>
    
    <ul class="right">
        <% if logged_in? %>
            <% user = User.find_by(id: post.user_id) %>
            <li class="italic">
                <span class="bold">Author: </span>
                <span class="capitalize"><%= user.username %></span>
            </li>
        <% end %>
        
        <li class="date"><span class="bold">Date: </span><%= post.created_at %></li>
    </ul>
</div>
<% end %>

<%= will_paginate %>

app/views/posts/new.html.erb
<h1>Write a New Article</h1>


 <div class="col-md-6 col-md-offset-3 new-post"> 

    <%= form_for(@post, url: posts_path(@post), html: { method: :post }) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

     <%= f.label :content%>
     <%= f.text_area :content, size: '50x10' %>
     <%= f.submit "Publish", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="home">
    <h1>The Members Only App</h1>
    <h2>You can read members articles but to post you need to be a member!</h2>
    <p class="center">
        <% if logged_in? %>
            <%= link_to "Articles", posts_path ,class: "btn btn-primary btn-lg" %>
        <% else %>
            <%= link_to "Sign up", new_user_path ,class: "btn btn-primary btn-lg" %>
        <% end %>
    </p>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

 <div class="col-md-6 col-md-offset-3 new-post"> 

    <%= form_for(@user, url: users_path(@user), html: { method: :post }) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

     <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>
     
     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %>
     
     <%= f.label :password_confirmation %>
     <%= f.password_field :password_confirmation, class: 'form-control' %>


     <%= f.submit "Sign up", class: "btn btn-primary" %>
    <% end %>
</div>